
THEME_KITCHEN
        BYTE COL_BROWN
        BYTE COL_MGREY
        BYTE COL_DGREY
        BYTE SRC_WOOD_00, SRC_WOOD_01, SRC_WOOD_02
        BYTE SRC_WOOD_03, SRC_WOOD_04, SRC_WOOD_05
        BYTE SRC_WOOD_06, SRC_WOOD_07, SRC_WOOD_08
        BYTE SRC_WALL_09, SRC_WALL_10, SRC_WALL_11
        BYTE SRC_WALL_12, SRC_WALL_13, SRC_WALL_14
        BYTE SRC_WALL_15, SRC_WALL_16, SRC_WALL_17
        BYTE SRC_CHECK_00, SRC_CHECK_01, SRC_CHECK_02
        BYTE CH_BLANK, CH_BLANK, CH_BLANK

        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02 ; Wall chars 
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_ORANGE, COL_ORANGE, COL_ORANGE ; Wall FG colours
        BYTE COL_ORANGE, COL_ORANGE, COL_ORANGE
        BYTE COL_ORANGE, COL_ORANGE, COL_ORANGE  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17 
        BYTE COL_RED, COL_RED, COL_RED
        BYTE COL_RED, COL_RED, COL_RED
        BYTE COL_RED, COL_RED, COL_RED 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        
        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02 ; Wall chars 
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_RED, COL_RED, COL_RED ; Wall FG colours
        BYTE COL_RED, COL_RED, COL_RED
        BYTE COL_RED, COL_RED, COL_RED  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17 
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_THEME_18, CH_THEME_18, CH_THEME_18 ; Floor chars
        BYTE CH_THEME_18, CH_THEME_19, CH_THEME_18
        BYTE CH_THEME_20, CH_THEME_18, CH_THEME_18 
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_BLANK, CH_THEME_20, CH_THEME_18 ; Floor chars
        BYTE CH_THEME_18, CH_THEME_18, CH_THEME_19
        BYTE CH_THEME_18, CH_THEME_18, CH_THEME_19
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_THEME_20, CH_THEME_18, CH_THEME_18 ; Floor chars
        BYTE CH_THEME_18, CH_BLANK, CH_BLANK
        BYTE CH_THEME_18, CH_THEME_18, CH_THEME_19 
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_THEME_18, CH_THEME_20, CH_BLANK ; Floor chars
        BYTE CH_THEME_19, CH_THEME_20, CH_THEME_19
        BYTE CH_BLANK, CH_THEME_18, CH_THEME_18 
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3  

THEME_FOREST
        BYTE COL_GREEN                          ; Background colour 2
        BYTE COL_ORANGE                         ; Background colour 3
        BYTE COL_BROWN                          ; Floor FG colour        
        BYTE SRC_BUSH_00, SRC_BUSH_01, SRC_BUSH_02, SRC_BUSH_03, SRC_BUSH_04, SRC_BUSH_05             ; Source chars
        BYTE SRC_BUSH_06, SRC_BUSH_07, SRC_BUSH_08, SRC_TREE_00, SRC_TREE_01, SRC_TREE_02
        BYTE SRC_TREE_03, SRC_TREE_04, SRC_TREE_05, SRC_TREE_06, SRC_TREE_07, SRC_TREE_08
        BYTE SRC_GRASS_00, SRC_GRASS_01, SRC_GRASS_02, SRC_GRASS_00, SRC_GRASS_01, SRC_GRASS_02

        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02 ; Wall chars 
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN ; Wall FG colours
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2           

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_3, BG_COL_2
        BYTE BG_COL_2, BG_COL_3, BG_COL_2 

        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2           

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_3, BG_COL_2
        BYTE BG_COL_2, BG_COL_3, BG_COL_2 

        BYTE CH_BLANK, CH_BLANK, CH_BLANK ; Floor chars
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  ; Floor FG colours
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 ; Floor BG colours
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3           

        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_THEME_18, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE COL_BROWN, COL_GREEN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3     

        BYTE CH_BLANK, CH_BLANK, CH_BLANK 
        BYTE CH_BLANK, CH_THEME_19, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_GREEN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 

        BYTE CH_BLANK, CH_BLANK, CH_BLANK 
        BYTE CH_BLANK, CH_THEME_20, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_GREEN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 

THEME_CASTLE
        BYTE COL_MGREY                          ; Background colour 2
        BYTE COL_ORANGE                         ; Background colour 3
        BYTE COL_BROWN                          ; Floor FG colour        

        BYTE SRC_WALL_09, SRC_WALL_10, SRC_WALL_11
        BYTE SRC_WALL_12, SRC_WALL_13, SRC_WALL_14
        BYTE SRC_WALL_15, SRC_WALL_16, SRC_WALL_17

        BYTE SRC_WINDOW_00, SRC_WINDOW_01, SRC_WINDOW_02
        BYTE SRC_WINDOW_03, SRC_WINDOW_04, SRC_WINDOW_05
        BYTE SRC_WINDOW_06, SRC_WINDOW_07, SRC_WINDOW_08

        BYTE SRC_COBBLE_00, SRC_COBBLE_01, SRC_COBBLE_02
        BYTE SRC_COBBLE_05, SRC_GRASS_00, SRC_GRASS_01

        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02 ; Wall chars 
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_MGREY, COL_MGREY, COL_MGREY ; Wall FG colours
        BYTE COL_MGREY, COL_MGREY, COL_MGREY
        BYTE COL_MGREY, COL_MGREY, COL_MGREY  
        BYTE BG_COL_1, BG_COL_1, BG_COL_1 ; Wall BG colours 
        BYTE BG_COL_1, BG_COL_1, BG_COL_1
        BYTE BG_COL_1, BG_COL_1, BG_COL_1           

        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02 ; Wall chars 
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_LGREY, COL_LGREY, COL_LGREY ; Wall FG colours
        BYTE COL_LGREY, COL_LGREY, COL_LGREY
        BYTE COL_LGREY, COL_LGREY, COL_LGREY  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14 
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17
        BYTE COL_MGREY, COL_MGREY, COL_MGREY ; Wall FG colours
        BYTE COL_MGREY, COL_BLUE, COL_MGREY
        BYTE COL_MGREY, COL_MGREY, COL_MGREY  
        BYTE BG_COL_1, BG_COL_1, BG_COL_1 ; Wall BG colours 
        BYTE BG_COL_1, BG_COL_3, BG_COL_1
        BYTE BG_COL_1, BG_COL_1, BG_COL_1           

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14 
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17
        BYTE COL_LGREY, COL_LGREY, COL_LGREY ; Wall FG colours
        BYTE COL_LGREY, COL_LBLUE, COL_LGREY
        BYTE COL_LGREY, COL_LGREY, COL_LGREY  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_3, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2


        BYTE CH_THEME_18, CH_THEME_19, CH_BLANK       ; Floor chars
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3     

        BYTE CH_BLANK, CH_BLANK, CH_BLANK       ; Floor chars
        BYTE CH_BLANK, CH_THEME_20, CH_THEME_21
        BYTE CH_BLANK, CH_BLANK, CH_THEME_23
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_GREEN
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3    

        BYTE CH_BLANK, CH_THEME_20, CH_THEME_19        ; Floor chars
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_THEME_23, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_GREEN, COL_GREEN, COL_BROWN
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_BLANK, CH_BLANK, CH_BLANK       ; Floor chars
        BYTE CH_BLANK, CH_THEME_22, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_GREEN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3


THEME_DESERT
        BYTE COL_ORANGE                          ; Background colour 2
        BYTE COL_YELLOW                         ; Background colour 3
        BYTE COL_ORANGE                          ; Floor FG colour        

        BYTE SRC_ROCK_00, SRC_ROCK_01, SRC_ROCK_02
        BYTE SRC_ROCK_03, SRC_ROCK_04, SRC_ROCK_05
        BYTE SRC_ROCK_06, SRC_ROCK_07, SRC_ROCK_08

        BYTE SRC_SAND_00, SRC_SAND_01, SRC_SAND_02
        BYTE SRC_SAND_03, SRC_SAND_04, SRC_SAND_05
        BYTE SRC_SAND_06, SRC_SAND_07, SRC_SAND_08

        BYTE SRC_CACTUS_00, SRC_CACTUS_01, SRC_CACTUS_02
        BYTE SRC_CACTUS_03, SRC_GRASS_00, SRC_GRASS_01

        BYTE CH_THEME_00, CH_THEME_01, CH_THEME_02 ; Wall chars 
        BYTE CH_THEME_03, CH_THEME_04, CH_THEME_05 
        BYTE CH_THEME_06, CH_THEME_07, CH_THEME_08 
        BYTE COL_BROWN, COL_BROWN, COL_BROWN ; Wall FG colours
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2           

        BYTE CH_THEME_09, CH_THEME_10, CH_THEME_11
        BYTE CH_THEME_12, CH_THEME_13, CH_THEME_14 
        BYTE CH_THEME_15, CH_THEME_16, CH_THEME_17
        BYTE COL_ORANGE, COL_ORANGE, COL_ORANGE ; Wall FG colours
        BYTE COL_ORANGE, COL_ORANGE, COL_ORANGE
        BYTE COL_ORANGE, COL_ORANGE, COL_ORANGE  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 ; Wall BG colours 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3            

        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_THEME_18, CH_THEME_19, CH_THEME_20
        BYTE CH_BLANK, CH_THEME_21, CH_BLANK
        BYTE COL_GREEN, COL_GREEN, COL_GREEN ; Wall FG colours
        BYTE COL_GREEN, COL_GREEN, COL_GREEN
        BYTE COL_GREEN, COL_GREEN, COL_GREEN  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 ; Wall BG colours 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3           

        BYTE CH_THEME_18, CH_THEME_19, CH_THEME_20
        BYTE CH_BLANK, CH_THEME_21, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE COL_GREEN, COL_GREEN, COL_GREEN ; Wall FG colours
        BYTE COL_GREEN, COL_GREEN, COL_GREEN
        BYTE COL_GREEN, COL_GREEN, COL_GREEN  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 ; Wall BG colours 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3    


        BYTE CH_BLANK, CH_THEME_22, CH_BLANK       ; Floor chars
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3     

        BYTE CH_BLANK, CH_BLANK, CH_BLANK       ; Floor chars
        BYTE CH_BLANK, CH_BLANK, CH_THEME_23
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3    

        BYTE CH_BLANK, CH_BLANK, CH_BLANK       ; Floor chars
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_THEME_23, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_BLANK, CH_BLANK, CH_BLANK       ; Floor chars
        BYTE CH_THEME_22, CH_BLANK, CH_BLANK
        BYTE CH_BLANK, CH_BLANK, CH_BLANK
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE COL_BROWN, COL_BROWN, COL_BROWN
        BYTE BG_COL_3, BG_COL_3, BG_COL_3 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3


THEME_SPACE
        BYTE COL_LGREY
        BYTE COL_MGREY
        BYTE COL_BLUE
        BYTE SRC_SPACE_WALL_00, SRC_SPACE_WALL_01, SRC_SPACE_WALL_02
        BYTE SRC_SPACE_WALL_03, SRC_SPACE_WINDOW_00, SRC_SPACE_WINDOW_01
        BYTE SRC_SPACE_WINDOW_02, SRC_SPACE_WINDOW_03, SRC_SPACE_WINDOW_04
        BYTE SRC_SPACE_WINDOW_05, SRC_SPACE_WINDOW_06, SRC_SPACE_WINDOW_07
        BYTE SRC_SPACE_WINDOW_08, SRC_LINE_00, SRC_LINE_01
        BYTE SRC_LINE_02, SRC_LINE_03, SRC_LINE_04
        BYTE SRC_LINE_05, SRC_LINE_06, SRC_LINE_07
        BYTE SRC_LINE_08, SRC_LINE_09, SRC_LINE_10

        BYTE CH_THEME_00, CH_THEME_00, CH_THEME_00 ; Wall chars 
        BYTE CH_THEME_13, CH_THEME_16, CH_THEME_23
        BYTE CH_THEME_01, CH_THEME_01, CH_THEME_01 
        BYTE COL_DGREY, COL_DGREY, COL_DGREY ; Wall FG colours
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE
        BYTE COL_DGREY, COL_DGREY, COL_DGREY  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2

        BYTE CH_THEME_02, CH_THEME_22, CH_THEME_03 ; Wall chars 
        BYTE CH_THEME_02, CH_THEME_15, CH_THEME_03 
        BYTE CH_THEME_02, CH_THEME_21, CH_THEME_03 
        BYTE COL_DGREY, COL_BLUE, COL_DGREY ; Wall FG colours
        BYTE COL_DGREY, COL_BLUE, COL_DGREY
        BYTE COL_DGREY, COL_BLUE, COL_DGREY  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        
        BYTE CH_THEME_04, CH_THEME_05, CH_THEME_06 ; Wall chars 
        BYTE CH_THEME_07, CH_THEME_08, CH_THEME_09 
        BYTE CH_THEME_10, CH_THEME_11, CH_THEME_12
        BYTE COL_DGREY, COL_DGREY, COL_DGREY ; Wall FG colours
        BYTE COL_DGREY, COL_WHITE, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_0, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2

        BYTE CH_THEME_04, CH_THEME_00, CH_THEME_06 ; Wall chars 
        BYTE CH_THEME_02, CH_STOVE, CH_THEME_03 
        BYTE CH_THEME_10, CH_THEME_01, CH_THEME_12
        BYTE COL_DGREY, COL_DGREY, COL_DGREY ; Wall FG colours
        BYTE COL_DGREY, COL_DGREY, COL_DGREY
        BYTE COL_DGREY, COL_DGREY, COL_DGREY  
        BYTE BG_COL_2, BG_COL_2, BG_COL_2 ; Wall BG colours 
        BYTE BG_COL_2, BG_COL_2, BG_COL_2
        BYTE BG_COL_2, BG_COL_2, BG_COL_2

        BYTE CH_THEME_15, CH_THEME_18, CH_THEME_17 ; Floor chars 
        BYTE CH_THEME_22, CH_THEME_23, CH_THEME_14 
        BYTE CH_THEME_21, CH_THEME_18, CH_THEME_23 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_THEME_22, CH_THEME_16, CH_THEME_13 ; Floor chars 
        BYTE CH_THEME_23, CH_THEME_13, CH_THEME_23 
        BYTE CH_THEME_13, CH_THEME_20, CH_THEME_18 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_THEME_14, CH_THEME_21, CH_THEME_18 ; Floor chars 
        BYTE CH_THEME_19, CH_THEME_21, CH_THEME_15 
        BYTE CH_THEME_13, CH_THEME_23, CH_THEME_14 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE  
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3

        BYTE CH_THEME_14, CH_THEME_16, CH_THEME_14 ; Floor chars 
        BYTE CH_THEME_15, CH_THEME_18, CH_THEME_21 
        BYTE CH_THEME_14, CH_THEME_23, CH_THEME_23 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE 
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE
        BYTE COL_PURPLE, COL_PURPLE, COL_PURPLE 
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3
        BYTE BG_COL_3, BG_COL_3, BG_COL_3  
