	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
MAP_CASTLE_01
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_PLATE,	TILE_MEAT,	TILE_BUN,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_2,	TILE_FLOOR_2,	TILE_FLOOR_1,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_BLOCKER_3,	TILE_BLOCKER_2,	TILE_WALL_2,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	TILE_FLOOR_3,	TILE_FLOOR_0,	TILE_FLOOR_3,	TILE_FLOOR_3,	TILE_FLOOR_3,	TILE_FLOOR_3,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_0,	TILE_CHOP,	TILE_FLOOR_1,	TILE_FLOOR_1,	TILE_FLOOR_1,	TILE_BIN,	TILE_SLIDER_N,	TILE_WALL_0,	TILE_BIN,	TILE_FLOOR_2,	TILE_FLOOR_2,	TILE_STOVE,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_0,	TILE_STOVE,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_BLOCKER_3,	TILE_BLOCKER_1,	TILE_SERVE,	TILE_SERVE,	TILE_BLOCKER_0,	TILE_BLOCKER_2,	TILE_FLOOR_0,	TILE_CHOP,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_BIN,	TILE_SLIDER_N,	TILE_SLIDER_S,	TILE_BIN,	TILE_FLOOR_3,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_2,	TILE_BLOCKER_1,	TILE_BLOCKER_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_3,	TILE_FLOOR_3,	TILE_WALL_2,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_LETTUCE,	TILE_TOMATO,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	$FF

	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

