	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
MAP_FOREST_03
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_BENCH,	TILE_SERVE,	TILE_BENCH,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_BUN,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_BIN,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_BLOCKER_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_MEAT,	$FF
	BYTE TILE_TOMATO,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_BLOCKER_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_PLATE,	$FF
	BYTE TILE_LETTUCE,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_CHOP,	TILE_CHOP,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_STOVE,	TILE_BENCH,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	$FF

	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

