	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
MAP_FOREST_04
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_BENCH,	TILE_BENCH,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_MEAT,	TILE_PLATE,	TILE_BUN,	TILE_VOID,	$FF
	BYTE TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	TILE_WALL_0,	TILE_TOMATO,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_LETTUCE,	$FF
	BYTE TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_3,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_WALL_1,	$FF
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_STOVE,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_SLIDER_E,	TILE_SLIDER_E,	TILE_SLIDER_E,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_CHOP,	TILE_WALL_0,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_WALL_3,	TILE_STOVE,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_SLIDER_W,	TILE_SLIDER_W,	TILE_SLIDER_W,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_CHOP,	TILE_WALL_0,	TILE_VOID,	$FF
	BYTE TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_3,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	TILE_WALL_0,	TILE_BENCH,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_WALL_0,	$FF
	BYTE TILE_VOID,	TILE_BIN,	TILE_WALL_3,	TILE_SERVE,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_1,	TILE_WALL_0,	TILE_WALL_1,	TILE_WALL_0,	TILE_VOID,	$FF

	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

