	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
MAP_FOREST_02
	BYTE TILE_VOID,	TILE_SERVE,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_BENCH,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	$FF
	BYTE TILE_CHOP,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_STOVE,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_WALL_0,	$FF
	BYTE TILE_BENCH,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_MEAT,	$FF
	BYTE TILE_BIN,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_FLOOR_2,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_TOMATO,	$FF
	BYTE TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_2,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_LETTUCE,	$FF
	BYTE TILE_VOID,	TILE_WALL_1,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_3,	TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_WALL_0,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_3,	TILE_PLATE,	TILE_BUN,	TILE_WALL_1,	TILE_VOID,	$FF

	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

