	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
MAP_SPACE_03
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_BENCH,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	TILE_VOID,	$FF
	BYTE TILE_LETTUCE,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_SERVE,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_BENCH,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_TOMATO,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_BLOCKER_1,	TILE_WALL_0,	$FF
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_BLOCKER_2,	TILE_WALL_0,	TILE_PLATE,	TILE_WALL_0,	TILE_WALL_0,	TILE_STOVE,	TILE_WALL_0,	TILE_WALL_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_WALL_1,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_BLOCKER_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_BLOCKER_3,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_0,	$FF
	BYTE TILE_MEAT,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_FLOOR_0,	TILE_WALL_1,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_0,	TILE_CHOP,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	TILE_BUN,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

