	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
MAP_SPACE_02
	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_WALL_0,	TILE_WALL_2,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_1,	TILE_MEAT,	TILE_TOMATO,	TILE_PLATE,	TILE_LETTUCE,	TILE_BUN,	TILE_WALL_1,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_2,	TILE_FLOOR_2,	TILE_FLOOR_3,	TILE_FLOOR_2,	TILE_FLOOR_3,	TILE_FLOOR_2,	TILE_FLOOR_3,	TILE_FLOOR_2,	TILE_WALL_2,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_1,	TILE_FLOOR_3,	TILE_FLOOR_2,	TILE_FLOOR_3,	TILE_FLOOR_2,	TILE_FLOOR_3,	TILE_FLOOR_2,	TILE_FLOOR_3,	TILE_WALL_1,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_WALL_0,	TILE_WALL_0,	TILE_BLOCKER_1,	TILE_BLOCKER_0,	TILE_BLOCKER_1,	TILE_WALL_0,	TILE_WALL_0,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_WALL_1,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_VOID,	TILE_WALL_1,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_FLOOR_0,	TILE_FLOOR_1,	TILE_WALL_1,	TILE_VOID,	TILE_VOID,	$FF
	BYTE TILE_VOID,	TILE_WALL_1,	TILE_VOID,	TILE_WALL_0,	TILE_STOVE,	TILE_BENCH,	TILE_SERVE,	TILE_BENCH,	TILE_CHOP,	TILE_WALL_0,	TILE_VOID,	TILE_WALL_1,	TILE_VOID,	$FF

	BYTE TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	TILE_VOID,	$FF

